In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [6]:
data = {'age' : [23,37,48,52,28,25,35,32,20,40],
        'Income' : [50000,34000,40000,30000,95000,78000,130000,105000,100000,60000],
        'target': [0,0,1,0,1,0,1,1,0,1]}

df = pd.DataFrame(data)

df

age  Income  target
0   23   50000       0
1   37   34000       0
2   48   40000       1
3   52   30000       0
4   28   95000       1
5   25   78000       0
6   35  130000       1
7   32  105000       1
8   20  100000       0
9   40   60000       1

In [35]:
def get_normalized_X_y(df_test):
    df_test.dropna(inplace=True)
    scaler = StandardScaler()
    scaler.fit(df_test.drop('target', axis=1))
    scaled_features = scaler.transform(df_test.drop('target',axis=1))
    df_test_feat = pd.DataFrame(scaled_features, columns = df_test.columns[:-1])
    y = df_test.iloc[:,-1].squeeze()
    X = df_test_feat
    return X, y

In [36]:
X,y = get_normalized_X_y(df)

In [37]:
X

age    Income
0 -1.097807 -0.679895
1  0.299402 -1.169909
2  1.397208 -0.986154
3  1.796411 -1.292413
4 -0.598804  0.698270
5 -0.898205  0.177630
6  0.099801  1.770177
7 -0.199601  1.004529
8 -1.397208  0.851400
9  0.598804 -0.373636

In [38]:
def train_test_data (X,y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

    return  X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_data(X,y)

X_train.shape,X_test.shape, y_train.shape, y_test.shape

((9, 2), (1, 2), (9,), (1,))

In [39]:
def knn_trainer(X_train, y_train, n):
    knn = KNeighborsClassifier(n_neighbors=n)

    knn.fit(X_train, y_train)

    return knn
knn = knn_trainer(X_train, y_train, n= 1)

In [40]:
knn.predict(X_test)

array([1], dtype=int64)

In [41]:
knn.score(X_test, y_test)

0.0

In [42]:
X_test

age  Income
8 -1.397208  0.8514

In [43]:
y_test

8    0
Name: target, dtype: int64

In [44]:
data2 = {'age': [50],
         'Income': [80000]}

df2 = pd.DataFrame(data2)

In [45]:
X

age    Income
0 -1.097807 -0.679895
1  0.299402 -1.169909
2  1.397208 -0.986154
3  1.796411 -1.292413
4 -0.598804  0.698270
5 -0.898205  0.177630
6  0.099801  1.770177
7 -0.199601  1.004529
8 -1.397208  0.851400
9  0.598804 -0.373636

In [46]:
knn.predict(df2)

array([1], dtype=int64)

### Ohne Skalieren

In [30]:
y = df.iloc[:,-1].squeeze()
X = df.drop('target', axis=1)

In [31]:
X_train, X_test, y_train, y_test = train_test_data(X,y)

In [32]:
knn = knn_trainer(X_train, y_train, n= 1)

In [34]:
knn.predict(df2)

array([0], dtype=int64)